VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "CFoundationSlabUIDTO"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "RSAPFootings.03_FoundationSlab"
'@IgnoreModule EncapsulatePublicField
'@IgnoreModule MoveFieldCloserToUsage
'@IgnoreModule VariableNotUsed
Option Explicit

Public typeOfFoundation As String

Public width As Double

Public lenth As Double

Public offset As Double

Public foundationThickness As Double

Public slabSectionName As String

